version: 0.2
  #AWS CodeBuild
env:
  variables:
    INPUT_FILE: template.yaml
    CONFIG_FILE: configuration.json
    OUTPUT_FILE: packaged-template.yaml
phases:
  # prebuild:
  build:
    commands:
    - sam build --template $INPUT_FILE
  install:
    commands:
    - aws cloudformation package --template $INPUT_FILE --s3-bucket $PACKAGE_BUCKET --output-template $OUTPUT_FILE
  # postbuild:

artifacts:
  files:
  - $INPUT_FILE
  - $OUTPUT_FILE
  - $CONFIG_FILE
  discard-paths: no